.\" Copyright (c) 2015 A.D. Isaac Dunham, no rights reserved
.\" Released under the libsysdev license
.TH "DEVINFO" 1 2015 "libsysdev"
.SH NAME
devinfo \- print information about a device
.SH SYNOPSIS
.BI "devinfo " /dev/node " ..."
.SH DESCRIPTION
.BR devinfo
prints the corresponding sysfs path and (if applicable)
the PCI IDs for the hardware.
.SH EXAMPLE
.SS Example 1 shows the PCI IDs of the primary graphics card:
.nf
$ devinfo /dev/dri/card0
/sys//devices/pci0000:00/0000:00:02.0/drm/card0/device	8086	27AE 
.fi

.SS Example 2 shows the "name" assigned by the kernel to each input device:
.nf
$ for i in `devinfo /dev/input/* |cut -f1`; do cat "$i"/name; done
AT Translated Set 2 keyboard
HDA Digital PCBeep
HDA VIA VT82xx Front Headphone
HDA VIA VT82xx Line Out CLFE
.fi
