.\" Copyright (c) 2015 A.D. Isaac Dunham, no rights reserved
.\" Released under the libsysdev license
.TH "DEVINFO" 1 2015 "libsysdev"
.SH NAME
devinfo \- print information about a device
.SH SYNOPSIS
devinfo /dev/node
.SH DESCRIPTION
\fIdevinfo\fP prints the corresponding sysfs path and (if applicable)
the PCI IDs for the hardware.
.SH EXAMPLE
$ \fB devinfo /dev/dri/card0 \fP 
/sys//devices/pci0000:00/0000:00:02.0/drm/card0/device	8086	27AE 

$ \fB for i in /dev/input/*; do cat `devinfo $i`/name; done \fP

Example 1 shows the PCI IDs of the primary graphics card.
Example 2 shows the "name" assgned by the kernel to each input device.
